name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0  

    - name: Build and test
<<<<<<< HEAD
      run: xcodebuild -quiet clean build test -project EssentialFeed2.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES && xcodebuild -quiet clean build test -project EssentialFeed2.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro Max" ONLY_ACTIVE_ARCH=YES
=======
      run: xcodebuild -quiet clean build test -project EssentialFeed2.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk macosx -destination "platform=macOS,name:My Mac" ONLY_ACTIVE_ARCH=YES && xcodebuild -quiet clean build test -project EssentialFeed2.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator, id=CF36F4A2-833F-4FCB-8ACF-4DFF4344367A, OS=18.2, name=iPhone 16 Pro Max" ONLY_ACTIVE_ARCH=YES
>>>>>>> origin/main
      
