name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0  

    - name: Build and test
      run: xcodebuild -quiet clean build test -project EssentialFeed2.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk macosx -destination "platform=macOS,name=My Mac" ONLY_ACTIVE_ARCH=YES && xcodebuild -quiet clean build test -project EssentialFeed2.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator, id=EFE2944A-56A8-4862-8579-745D4DA4B0F0, OS=18.2, name=iPhone 16" ONLY_ACTIVE_ARCH=YES
      
